apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: modelmesh

resources:
  - api-deployment.yaml

commonLabels:
  app.kubernetes.io/name: modelmesh
  app.kubernetes.io/managed-by: kustomize
